### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by saravanabalagi**
Adding "The University of Edinburgh"
Tested and it works without any flaws (Downloaded videos today)

Added logos from universities' website sources

### CODE REVIEW

**Review by ericjiang97 — APPROVED** [review]
Thanks for you PR! 👏 
Awesome work

**Comment by saravanabalagi** [comment]
@lorderikir could you please add "The University of Edinburgh" to Wiki/Supported Institutions/UK Institutions?

**Comment by ericjiang97** [comment]
Awesome. Done.

**Comment by saravanabalagi** [comment]
👍 Cheers

**Pull request merged**
