### PR TITLE
add the ability to download direct url if not hls

### PR DESCRIPTION
**Pull request by CT1994**
this is to fix the issue where the filename is not the expected format of hd{sourceIndex}.mp4

### CODE REVIEW

**Comment by CT1994** [comment]
@imaginebreake here is the fix for the issue you raised

**Comment by breakertt** [comment]
Test passed, please merge @ericjiang97 .
@CT1994 Thank you!

**Comment by CT1994** [comment]
@imaginebreake could you retest I have also fixed the following issue
https://github.com/GeckoDM/GeckoDownloadManager/issues/72

@hugobene
@sethb3744
@ericjiang97

**Review by ericjiang97 — APPROVED** [review]
Lgtm

**Comment by CT1994** [comment]
@ericjiang97 I've done a small cleanup where i did not like picking the script tag out of the html page so i filter to find the data i am looking for

**Review by ericjiang97 — APPROVED** [review]

**Pull request merged**
