### PR TITLE
Split by space to get unitcode if there is a space.

### LINKED ISSUE #38: Macquarie Echo360 doesn't function
Fresh public chrome build install, latest GeckoDM install from chrome app store. Echo360 is run through iLearn and not Blackboard.

Files appear in list but do not start download when button pressed.

### PR DESCRIPTION
**Pull request by darvid7**
Hopefully this fixes #38 otherwise ill be sad

### CODE REVIEW

**Comment by ericjiang97** [comment]
Lol.....im not sure if we should merge this one in.

Thinking either we prompt user to select a unit/add unit to a predefined list. Then download without changing the filename to that directory.

**Comment by ericjiang97** [comment]
@darvid7 has this been tested yet?

**Comment by darvid7** [comment]
What? We are not changing file name? We are just trying to get the unit code. Have a look at the issue.

**Comment by callistusystan** [comment]
Yeah, this makes sense to me. Thanks for the fix, @darvid7

**Review by callistusystan — APPROVED** [review]
Looks good to me.

**Pull request merged**
